// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaqnF6yXChsjJy52YWyMDVSJnNo0P865Q',
    appId: '1:1083021889823:web:33bacbfddfa15b0c17e02a',
    messagingSenderId: '1083021889823',
    projectId: 'wm-teknoloji-haber',
    authDomain: 'wm-teknoloji-haber.firebaseapp.com',
    storageBucket: 'wm-teknoloji-haber.appspot.com',
    databaseURL: 'https://wm-teknoloji-haber.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBLQ-bkzhK_pUIKNu9Hmo0Rq5jlM0h7q0',
    appId: '1:1083021889823:android:f4fa9b9f4d22741d17e02a',
    messagingSenderId: '1083021889823',
    projectId: 'wm-teknoloji-haber',
    storageBucket: 'wm-teknoloji-haber.appspot.com',
    databaseURL: 'https://wm-teknoloji-haber.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN0m_7bGOpTHW9wX4xUnLkoWRVQG2JvgY',
    appId: '1:1083021889823:ios:f322bece985b527017e02a',
    messagingSenderId: '1083021889823',
    projectId: 'wm-teknoloji-haber',
    storageBucket: 'wm-teknoloji-haber.appspot.com',
    databaseURL: 'https://wm-teknoloji-haber.firebaseio.com',
    iosBundleId: 'com.example.wmorgtrNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN0m_7bGOpTHW9wX4xUnLkoWRVQG2JvgY',
    appId: '1:1083021889823:ios:f322bece985b527017e02a',
    messagingSenderId: '1083021889823',
    projectId: 'wm-teknoloji-haber',
    storageBucket: 'wm-teknoloji-haber.appspot.com',
    databaseURL: 'https://wm-teknoloji-haber.firebaseio.com',
    iosBundleId: 'com.example.wmorgtrNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaqnF6yXChsjJy52YWyMDVSJnNo0P865Q',
    appId: '1:1083021889823:web:f8b938ed2d4f4c3217e02a',
    messagingSenderId: '1083021889823',
    projectId: 'wm-teknoloji-haber',
    authDomain: 'wm-teknoloji-haber.firebaseapp.com',
    storageBucket: 'wm-teknoloji-haber.appspot.com',
    databaseURL: 'https://wm-teknoloji-haber.firebaseio.com',
  );
}
